//
// Created by zfb457 on 2023/8/4.
//

#ifndef NATIVEINJECTOR_JAVA_DEF_H
#define NATIVEINJECTOR_JAVA_DEF_H

#define ARCH_ARM32 0
#define ARCH_ARM64 1
#define MODE_PLT_HOOK 0
#define MODE_INLINE_HOOK_UNIQUE 1
#define MODE_INLINE_HOOK_SHARED 2
#define MODE_SINGLE_INST_HOOK 3
#define MODE_PTRACE_TRAP_HOOK 4
#define MODE_NO_TRACE_HOOK 5
#define MODE_SO_INJECT 6

#endif //NATIVEINJECTOR_JAVA_DEF_H
